name: web automation workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    #download repo
    - uses: actions/checkout@v3
    
    #setup java jdk
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    #installing browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.4.0
       
    #setup gradle
    - name: setup gradlew
      run: chmod +x gradlew

    #execute gradle command to run cucumber test
    - name: execute test
      run: ./ gradlew cucumber
    
